package com.kinginsai.CRM.entity;
// Generated 2024-9-3 8:15:09 by Hibernate Tools 5.2.8.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="users"
    ,catalog="demo"
)
public class Users  implements java.io.Serializable {


     private String usersName;
     private String usersPassword;

    public Users() {
    }

    public Users(String usersName, String usersPassword) {
       this.usersName = usersName;
       this.usersPassword = usersPassword;
    }
   
     @Id 

    
    @Column(name="users_name", unique=true, nullable=false, length=64)
    public String getUsersName() {
        return this.usersName;
    }
    
    public void setUsersName(String usersName) {
        this.usersName = usersName;
    }

    
    @Column(name="users_password", nullable=false, length=64)
    public String getUsersPassword() {
        return this.usersPassword;
    }
    
    public void setUsersPassword(String usersPassword) {
        this.usersPassword = usersPassword;
    }




}


