package com.kinginsai.CRM.entity;
// Generated 2024-9-3 8:15:09 by Hibernate Tools 5.2.8.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Usersinfo generated by hbm2java
 */
@Entity
@Table(name="usersinfo"
    ,catalog="demo"
)
public class Usersinfo  implements java.io.Serializable {


     private String usersName;
     private String usersInfo;

    public Usersinfo() {
    }

    public Usersinfo(String usersName, String usersInfo) {
       this.usersName = usersName;
       this.usersInfo = usersInfo;
    }
   
     @Id 

    
    @Column(name="users_name", unique=true, nullable=false, length=64)
    public String getUsersName() {
        return this.usersName;
    }
    
    public void setUsersName(String usersName) {
        this.usersName = usersName;
    }

    
    @Column(name="users_info", nullable=false, length=64)
    public String getUsersInfo() {
        return this.usersInfo;
    }
    
    public void setUsersInfo(String usersInfo) {
        this.usersInfo = usersInfo;
    }




}


