package com.kinginsai.CRM.entity;
// Generated 2024-8-30 8:58:28 by Hibernate Tools 5.2.8.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Usersinfo generated by hbm2java
 */
@Entity
@Table(name="usersinfo"
    ,catalog="demo"
)
public class Usersinfo  implements java.io.Serializable {


     private String usersName;
     private Users users;
     private String usersInfo;

    public Usersinfo() {
    }

    public Usersinfo(Users users, String usersInfo) {
       this.users = users;
       this.usersInfo = usersInfo;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="users"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="users_name", unique=true, nullable=false, length=64)
    public String getUsersName() {
        return this.usersName;
    }
    
    public void setUsersName(String usersName) {
        this.usersName = usersName;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

    
    @Column(name="users_info", nullable=false, length=64)
    public String getUsersInfo() {
        return this.usersInfo;
    }
    
    public void setUsersInfo(String usersInfo) {
        this.usersInfo = usersInfo;
    }




}


