package com.kinginsai.CRM.entity;
// Generated 2024-8-30 8:58:28 by Hibernate Tools 5.2.8.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="users"
    ,catalog="demo"
)
public class Users  implements java.io.Serializable {


     private String usersName;
     private String usersPassword;
     private Usersinfo usersinfo;

    public Users() {
    }

	
    public Users(String usersName, String usersPassword) {
        this.usersName = usersName;
        this.usersPassword = usersPassword;
    }
    public Users(String usersName, String usersPassword, Usersinfo usersinfo) {
       this.usersName = usersName;
       this.usersPassword = usersPassword;
       this.usersinfo = usersinfo;
    }
   
     @Id 

    
    @Column(name="users_name", unique=true, nullable=false, length=64)
    public String getUsersName() {
        return this.usersName;
    }
    
    public void setUsersName(String usersName) {
        this.usersName = usersName;
    }

    
    @Column(name="users_password", nullable=false, length=64)
    public String getUsersPassword() {
        return this.usersPassword;
    }
    
    public void setUsersPassword(String usersPassword) {
        this.usersPassword = usersPassword;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="users")
    public Usersinfo getUsersinfo() {
        return this.usersinfo;
    }
    
    public void setUsersinfo(Usersinfo usersinfo) {
        this.usersinfo = usersinfo;
    }




}


