package com.kinginsai.CRM.entity;
// Generated 2024-8-30 8:58:28 by Hibernate Tools 5.2.8.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Usersdata generated by hbm2java
 */
@Entity
@Table(name="usersdata"
    ,catalog="demo"
)
public class Usersdata  implements java.io.Serializable {


     private String usersName;
     private String usersPassword;
     private String usersInfo;

    public Usersdata() {
    }

    public Usersdata(String usersName, String usersPassword, String usersInfo) {
       this.usersName = usersName;
       this.usersPassword = usersPassword;
       this.usersInfo = usersInfo;
    }
   
     @Id 

    
    @Column(name="users_name", unique=true, nullable=false, length=64)
    public String getUsersName() {
        return this.usersName;
    }
    
    public void setUsersName(String usersName) {
        this.usersName = usersName;
    }

    
    @Column(name="users_password", nullable=false, length=64)
    public String getUsersPassword() {
        return this.usersPassword;
    }
    
    public void setUsersPassword(String usersPassword) {
        this.usersPassword = usersPassword;
    }

    
    @Column(name="users_info", nullable=false, length=64)
    public String getUsersInfo() {
        return this.usersInfo;
    }
    
    public void setUsersInfo(String usersInfo) {
        this.usersInfo = usersInfo;
    }




}


